# For Scaleway.
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: game-retain
provisioner: csi.scaleway.com
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: game-delete
provisioner: csi.scaleway.com
reclaimPolicy: Delete
allowVolumeExpansion: true
