apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: factorio
spec:
  interval: 5m
  releaseName: factorio
  chart:
    spec:
      chart: factorio-server-charts
      version: "1.2.3"
      sourceRef:
        kind: HelmRepository
        name: factorio-server-charts
        namespace: flux-system
  values:
    persistence:
      enabled: true
      dataDir:
        size: 10Gi

    service:
      type: NodePort
      port: 34197
      nodePort: 34197

    factorioServer:
      save_name: kubesave

    rcon:
      external: true
      password: humanodehumanode
      port: 30100

    admin_list:
      - MOZGIII

    server_settings:
      name: Humanode
      tags:
        - modded
      visibility:
        public: false
      require_user_verification: false

    serverPassword:
      game_password: humanode

    account:
      accountSecret: factorio-token

    mods:
      enabled: true
      # in order to use the mods portal you will need to specify the username and token in the server_settings.
      # name is determined by the url, it will be the last part of the url, not the title of the mod.
      portal:
        # https://spaceexploration.miraheze.org/wiki/Recommended_Mods#Required_Dependencies
        # Recommended
        - ModuleInserterSimplified
        - aai-vehicles-ironclad
        - grappling-gun
        - bullet-trails
        - equipment-gantry
        - textplates
        - combat-mechanics-overhaul
        - RecipeBook
        - solar-calc
        # QOL
        - even-distribution
        - AutoTrash
        - LogisticRequestManager
        - BottleneckLite
        - Squeak Through
        - LogisticTrainNetwork
        # spaceX
        - alien-biomes
        - alien-biomes-hr-terrain
        - space-exploration-graphics
        - space-exploration-graphics-2
        - space-exploration-graphics-3
        - space-exploration-graphics-4
        - space-exploration-graphics-5
        - space-exploration-menu-simulations
        - shield-projector
        - aai-containers
        - aai-industry
        - aai-signal-transmission
        - simhelper
        - space-exploration-graphics
        - robot_attrition
        - informatron
        - jetpack
        - space-exploration-postprocess
        - space-exploration
      unofficial: []

    map_settings:
      difficulty_settings:
        research_queue_setting: "always"
      pollution:
        enabled: false
      enemy_evolution:
        enabled: false

    map_gen_settings:
      peaceful_mode: true
      water: 1.5
      starting_area: 2
      autoplace_controls:
        coal:
          frequency: 1
          size: 1
          richness: 3
        stone:
          frequency: 1
          size: 1
          richness: 3
        copper-ore":
          frequency: 1
          size: 1
          richness: 3
        iron-ore:
          frequency: 1
          size: 1
          richness: 3
        uranium-ore:
          frequency: 1
          size: 1
          richness: 3
        crude-oil:
          frequency: 1
          size: 1
          richness: 3
        trees:
          frequency: 1
          size: 1
          richness: 1
        enemy-base:
          frequency: 0
          size: 0
          richness: 0
      property_expression_names:
        control-setting:moisture:bias: "0.05"
        control-setting:aux:bias: "-0.35"
